# Generated by Django 3.0.5 on 2020-04-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_coo', '0002_auto_20200411_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
