# Generated by Django 3.0.5 on 2020-04-11 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('E_coo', '0004_orders_who_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='clicked_the_item_or_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='user_purchaser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
